### ISSUE TITLE
Should allow passing the list of hosts from the command line

### ISSUE THREAD

**Issue by dannyhajj** [sys0dm1n/varnish-cache-warmer#4]
We should allow passing the list of hosts from the command line instead.
This would allow users to call the script like so:

```bash
varnish-cache-warmer.sh x.x.x.x y.y.y.y z.z.z.z
```

**Comment by sys0dm1n** [comment]
Good suggestion, don't hesitate to contribute code wise if you got more good  ideas.
https://github.com/sys0dm1n/varnish-cache-warmer/commit/4e804194fcd33e2c7e04754120b96ec4475ce0fa
